In [1]:
import torch

In [2]:
import torch.nn as nn

In [3]:
class MyNN(nn.Module):
    def __init__(self):
        super(MyNN, self).__init__()
        self.linear = nn.Linear(10, 5)

    def forward(self, x):
        return self.linear(x)

In [4]:
my_nn = MyNN()
input_tensor = torch.ones((1, 10))
output_tensor = my_nn(input_tensor)
c = output_tensor.detach()
c.device


device(type='cpu')

In [5]:
print(output_tensor)
output_tensor[0, 0] = 100
print(c)
c.sin()
c.cos()
c.sin().square()+c.cos().square()
print(c.sin().unsqueeze(-1))
print(c.cos().unsqueeze(-1))
torch.concatenate([c.sin().unsqueeze(-1), c.cos().unsqueeze(-1)], dim=-1)

tensor([[ 0.5281, -0.1548,  0.8480, -0.2720, -0.0216]],
       grad_fn=<AddmmBackward0>)
tensor([[ 1.0000e+02, -1.5480e-01,  8.4799e-01, -2.7198e-01, -2.1551e-02]])
tensor([[[-0.5064],
         [-0.1542],
         [ 0.7500],
         [-0.2686],
         [-0.0215]]])
tensor([[[0.8623],
         [0.9880],
         [0.6615],
         [0.9632],
         [0.9998]]])


tensor([[[-0.5064,  0.8623],
         [-0.1542,  0.9880],
         [ 0.7500,  0.6615],
         [-0.2686,  0.9632],
         [-0.0215,  0.9998]]])

In [6]:
d = torch.ones((3, 4, 5))
d.shape
print(d.unsqueeze(0).shape)
print(d.unsqueeze(0))
print(d.unsqueeze(1).shape)
print(d.unsqueeze(1))

torch.Size([1, 3, 4, 5])
tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])
torch.Size([3, 1, 4, 5])
tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])


In [11]:
e = torch.zeros_like(d)
print(e)
f = torch.randn_like(d)
print(f)
g = torch.full_like(d, 3.14)
print(g)
h = torch.ones_like(d)
print(h)
print(torch.randn(1, 3))

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
tensor([[[ 0.1479, -1.3964, -0.3818, -0.5468,  0.6068],
         [-0.7115,  0.2797,  1.7876, -1.3835,  0.8740],
         [-1.5054, -0.2194, -0.8354,  0.0729, -0.8580],
         [ 1.3620, -0.2011,  0.7507, -1.9471,  0.1983]],

        [[-0.0381, -0.6047, -0.9636, -1.4835, -0.2492],
         [ 0.8840,  0.0954,  0.6157,  0.9611,  1.4297],
         [ 0.7369,  0.1462,  0.8229, -2.1268,  0.3300],
         [ 0.0740, -0.4021,  0.0927,  0.0670, -0.6221]],

        [[ 0.1355,  0.5805, -0.3232, -0.7365,  0.8265],
         [ 0.1422,  0.3041,  0.2420, -1.4315, -1.3683],
         [ 0.2813, -0.5938,  0.7443,  0.8691,  0.5338],
  